#%RAML 1.0 DataType

description : This is datatype file for report response

type: object
properties:
  message:
    type: string
    required: true
    example : "Report genrated for LID103"
  file_name : 
    type: string
    required: true
    example: "Report-LID103-2024-01-10T14:15:01.923+05:30.xlsx"