#%RAML 1.0 Library
usage: This is for the datatype of the report api

types:
  report-reponse: !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/report-response-datatype/1.0.0/report-response-datatype.raml